#
# This source file is part of the Stanford Biodesign for Digital Health open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford Biodesign for Digital Health and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Create and Upload Coverage Report

on:
  workflow_call:
    inputs:
      coveragereports:
        description: 'A string containing all names of the .xcresult files that are downloaded from the artifacts of previous jobs.'
        required: true
        type: string
    secrets:
      token:
        description: 'The CodeCov token used for private repositories'
        required: false

jobs:
  create-and-upload-coverage-report:
    name: Create and Upload Coverage Report
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Check Environment
      run: |
          xcodebuild -version
          swift --version
    - uses: actions/download-artifact@v3
    - name: Merge Coverage Reports
      run: |
          xcrun xcresulttool merge ${{ inputs.coveragereports }} --output-path CodeCoverage.xcresult
          rm -rf ${{ inputs.coveragereports }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        token: ${{ secrets.token }}
        xcode: true
        xcode_archive_path: CodeCoverage.xcresult